- name: configure backend server
  hosts: backend
  become: yes
  tasks:
    - name : disable current version of nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name : enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name : install nodejs
      ansible.builtin.package:
        name : nodejs
        state: present  # installed will be used for dnf module. for package it is present/absent
    
    - name: create expense user
      ansible.builtin.user:
        name: expense

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download backend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip
    
    - name: unzip backend code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        

   

