- name : Configure mysql
  hosts : mysql
  become : yes
  tasks :
    - name : task1 - Install mysql libraries
      ansible.builtin.pip:
        name : {{ item }} # This is a library for Python to connect to mysql
        executable: pip3.9
      loop:
        - PyMySQL
        - cryptography
    - name : task1 - Install mysql
      ansible.builtin.package :
        name : mysql-server
        state : installed

    - name : task2 - Start  and enable mysql service
      ansible.builtin.service :
        name : mysqld
        state : started
        enabled: yes
    
    - name : task3 - Conect to mysql server by setting root password
      community.mysql.mysql_info:
        login_user : root
        login_password : ExpenseApp@1
        login_host : mysql.vishnudevopsaws.online
      register : mysql_info
      ignore_errors: true

    - name : print the output
      ansible.builtin.debug:
        msg: " My SQL Info {{ mysql_info }} "
    
    - name : setup root password 
      ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"
      when : mysql_info.failed is true
